package com.example.bloogy.model;

import com.google.cloud.Timestamp;
import com.google.cloud.spring.data.firestore.Document;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Document
public class Feedback {

    @Id // Unique identifier for the feedback, automatically generated by Firestore
    private String id;

    private String articleId; // The ID of the article this feedback is related to
    private String commenterName; // The name of the person who provided the feedback
    private String comment; // The feedback content or message
    private Timestamp commentedDate; // The date and time the feedback was submitted
}
